#This pipeline can be triggered manually by giving the inputs or it can also be triggered automatically on push on main branch.
name: Deploy application on Hetzner Server

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Enter public IP of the server"
        required: true
  push:
    branches:
      - main

jobs:
  deploy-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Server IP
        id: set-server-ip
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "SERVER_IP=${{ github.event.inputs.server_ip }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "push" ]; then
            echo "SERVER_IP=${{ secrets.MY_SERVER_IP }}" >> $GITHUB_ENV
          fi

      - name: Check for change in src
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'src/**'
          base: ${{ github.event.before }}

      - name: Copy Latest Code
        if: steps.changes.outputs.src == 'true'
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "src/*"
          target: "/root/src"

      - name: Rebuild and Restart Containers
        if: steps.changes.outputs.src == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/src
            docker compose up -d --build --force-recreate

      - name: Docker Cleanup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # This command removes all unused containers, networks, images to free up system space
            docker system prune -af
